# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: rm -rf node_modules
    - run: npm install --legacy-peer-deps
    - run: |
      git config --global user.name 'hooktosky'
      git config --global user.email 'hande.akin123@gmail.com'
      git remote set-url origin git@github.com:HookToSky/hooktosky.github.io.git
      npm run deploy
  env:
    user_name: 'hooktosky'
    user_email: 'hande.akin123@gmail.com'
    github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    repository: 'hooktosky.github.io.git'
