# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: rm -rf node_modules
    - run: npm install --legacy-peer-deps
    - run: npm run build

  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: deploy to gh-pages
      uses: actions/setup-node@v3
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./build          
    - run: npm run deploy

  
  # deploy:
  #  - name: Deploy
  #   run: |
  #   git config --global user.name $user_name
  #   git config --global user.email $user_email
  #   git remote set-url origin https://${github_token}@github.com/${repository}
  #   npm run deploy
  # env:
  #   user_name: 'github-actions[bot]'
  #   user_email: 'github-actions[bot]@users.noreply.github.com'
  #   github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
  #   repository: ${{ github.repository }}
